CREATE TABLE IF NOT EXISTS blogs (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  excerpt TEXT NOT NULL,
  author TEXT NOT NULL,
  imageUrl TEXT NOT NULL,
  category TEXT NOT NULL,
  publishDate TEXT DEFAULT CURRENT_TIMESTAMP,
  readTime INTEGER NOT NULL
);
