name = "blogs-list-api"
main = "server.js"
compatibility_date = "2024-01-01"

[env.production]
name = "blogs-list-api"

[env.staging]
name = "blogs-list-api-staging"

[[env.production.vars]]
key = "ENVIRONMENT"
value = "production"

[[env.staging.vars]]
key = "ENVIRONMENT"
value = "staging"


[[d1_databases]]
binding = "DB"
database_name = "my-database"
database_id = "69714559-17e7-46e1-99f5-51bd7697a443"